title: Gathr - Personalized Product Experiences For Employees
apple-itunes-app: app-id=XXXXXXXXX
author: Gathr
description: Get free, personalized product experiences sent directly to your office so your team can feel great.
keywords: products, product, experiences, brands, samples, sampling, items, buy, test, marketplace
revisit-after: 7 days
og:
  title: Gathr - Personalized Product Experiences For Employees
  description: Get free, personalized product experiences sent directly to your office so your team can feel great.
  image: https://gathrnow.com/assets/img/group.jpg
  url: https://gathrnow.com
  site_name: Gathr
  type: website
twitter:
  card: summary_large_image
  image: https://gathrnow.com/assets/img/group.jpg
  domain: gathrnow.com
  title: Gathr - Personalized Product Experiences For Employees
  description: Get free, personalized product experiences sent directly to your office so your team can feel great.
